### ISSUE TITLE
Create a self-contained EAD Ref ID auto-increment ASpace plugin for archival objects

### ISSUE THREAD

**Issue by lorawoodford** [Smithsonian/caas_aspace_refid#1]
Main branch (backend functionality only, no regenerate): https://github.com/Smithsonian/caas_aspace_refid/tree/main

Branch with regenerate checkbox in UI: https://github.com/Smithsonian/caas_aspace_refid/tree/regenerate_ref_id

Still to coordinate.
Mark, to do:  provide an extract from PROD's SQLite database.  
George, to do: update ASpace TEST with PROD.
Lora, to do: conduct migrations and install plugin
All: test!
If all goes well, move to PROD (perhaps waiting for the upgrade to 3.5.1)

**Comment by fordmadox** [comment]
Update: Mark will get a CSV of the current Resource last IDs from George's ASpace SQL query, rather than from the SQL Lite database.
